### ISSUE TITLE
Unable to build chromium

### ISSUE THREAD

**Issue by onny** [Igalia/chromium#301]
Hey Igalia-team,
first of all thanks for your work! I really would like to test your Wayland patches.
I cloned your git repository, switched inside the chromium directory and run:
```
 $ gn args out/Ozone --args="use_ozone=true enable_package_mash_services=true use_xkbcommon=true"
gn.py: Could not find checkout in any parent of the current path.
This must be run inside a checkout.

```
Running
```
gclient runhooks
Error: client not configured; see 'gclient config'
```
also doesn't seem to solve the issue :( I guess I missed a step?

Best regards,
Jonas

**Comment by tonikitoo** [comment]
I believe you need something like this, at the directory parent of your checkour:

$ cd <my chromium checkout>
$ more ../.gclient
solutions = [
  {
    "url": "https://chromium.googlesource.com/chromium/src.git",
    "managed": False,
    "name": "src",
    "deps_file": ".DEPS.git",
    "custom_deps": {},
  },
]

**Comment by tonikitoo** [comment]
before the gn step (you pasted above), make sure you run

$ build/install-build-deps.sh # to be ran once .. if you are on ubuntu/debian it works best.

$ gclient sync # from within your chromium checkout.

**Comment by onny** [comment]
Can you post the contents of your ``../.gclient_entries`` file?
Thanks

**Comment by tonikitoo** [comment]
here it is:

https://gist.github.com/tonikitoo/acd5c858ee0b39acd77dd610b60f57a4

**Comment by tonikitoo** [comment]
Did it work?

**Comment by onny** [comment]
Thanks @tonikitoo for the support!
I got it working with these commands:
```
gclient config --name=src https://github.com/Igalia/chromium.git
gclient sync --with_branch_heads --nohooks
gclient runhooks

cd src

gn args out/Ozone --args="use_ozone=true enable_package_mash_services=true" # use_xkbcommon=true
ninja -C out/Ozone chrome
```

**Comment by tonikitoo** [comment]
thank you.

just one side note: running without xkbcommon crashes at startup for me.

**Comment by onny** [comment]
Yep for me too, I guess I have to fix this!

**Comment by tonikitoo** [comment]
Ok, I take it you can use xkbcommon, then. Patches welcomed :)

could you share a bit more your set up / target?

**Comment by onny** [comment]
Yep of course. I'm trying to get build a package for ArchLinux, see here: https://aur.archlinux.org/packages/chromium-wayland-git
Finally, my aim is to "port" Electron to run on Wayland: https://github.com/electron/electron/issues/10915

**Comment by onny** [comment]
Damn, looks like the debian sysroot doesn't contain xkbcommon:
```
________ running '/usr/bin/python2 src/third_party/gvr-android-sdk/test-apks/update.py' in '/home/onny/projects/chromium-wayland-git/src/chromium'
ERROR at //build/config/linux/pkg_config.gni:85:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: /home/onny/projects/chromium-wayland-git/src/chromium/src/out/Ozone/
Command: python -- /home/onny/projects/chromium-wayland-git/src/chromium/src/build/config/linux/pkg-config.py -s /home/onny/projects/chromium-wayland-git/src/chromium/src/build/linux/debian_wheezy_amd64-sysroot -a x64 xkbcommon
Returned 1.
stderr:

Package xkbcommon was not found in the pkg-config search path.
Perhaps you should add the directory containing `xkbcommon.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xkbcommon' found
Traceback (most recent call last):
  File "/home/onny/projects/chromium-wayland-git/src/chromium/src/build/config/linux/pkg-config.py", line 219, in <module>
    sys.exit(main())
  File "/home/onny/projects/chromium-wayland-git/src/chromium/src/build/config/linux/pkg-config.py", line 138, in main
    prefix = GetPkgConfigPrefixToStrip(args)
  File "/home/onny/projects/chromium-wayland-git/src/chromium/src/build/config/linux/pkg-config.py", line 80, in GetPkgConfigPrefixToStrip
    env=os.environ)
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['pkg-config', '--variable=prefix', 'xkbcommon']' returned non-zero exit status 1

See //ui/events/ozone/BUILD.gn:16:3: whence it was called.
  pkg_config("xkbcommon") {
  ^------------------------
See //ui/base/BUILD.gn:568:7: which caused the file to be included.
      "//ui/events/ozone:events_ozone_evdev",
      ^-------------------------------------
==> ERROR: A failure occurred in build().
    Aborting...
```
So I'm unable to build it yet :(

**Comment by tonikitoo** [comment]
I see to have it:

$ find build -name xkbcommon.pc
build/linux/debian_stretch_amd64-sysroot/usr/lib/pkgconfig/xkbcommon.pc
build/linux/debian_jessie_amd64-sysroot/usr/lib/pkgconfig/xkbcommon.pc
build/linux/debian_jessie_i386-sysroot/usr/lib/pkgconfig/xkbcommon.pc
build/linux/debian_jessie_arm64-sysroot/usr/lib/pkgconfig/xkbcommon.pc
build/linux/ubuntu_precise_amd64-sysroot/usr/lib/pkgconfig/xkbcommon.pc

**Comment by onny** [comment]
Me too :(
```
% pacman -Ql | grep xkbcommon.pc
lib32-libxkbcommon /usr/lib32/pkgconfig/xkbcommon.pc
libxkbcommon /usr/lib/pkgconfig/xkbcommon.pc
```

**Comment by tonikitoo** [comment]
Interesting. 'pacman' actually triggers a game on my Ubuntu 17.10 box :)

So you are trying build Chromium/Wayland on ArchLinux, and use the prebuilt Debian sysroot (in //build/linux/debian_jessie_amd64-sysroot/), but xkbcommon.pc isn't being picked up from there. Is that it?

Could you paste your GN args? For the record here are mine:

is_debug = false
is_component_build = false
symbol_level = 1
dcheck_always_on = true
use_ozone = true
ozone_platform_wayland = true
ozone_platform_x11 = true
ozone_platform_gbm = false
ozone_platform_headless = true
ozone_auto_platforms = false
use_xkbcommon = true
enable_mus = true
use_sysroot = true
treat_warnings_as_errors = false
is_clang = true
enable_nacl = false
remove_webcore_debug_symbols = true
use_jumbo_build = true
proprietary_codecs = true
ffmpeg_branding = "Chrome"

**Comment by onny** [comment]
Thanks for the answer. These are my arguments:
```
gn gen out/Ozone --args="use_ozone=true enable_package_mash_services=true use_xkbcommon=true use_system_libxkbcommon=1"
```

**Comment by tonikitoo** [comment]
Ok, I think this explains it a bit:

use_system_libxkbcommon=1 does not seem like a valid GN parameter

I believe you would need something similar to what is done by libdrm:

https://cs.chromium.org/search/?q=use_system_libdrm&sq=package:chromium&type=cs

or even better: you might want to disable the builtin sysroot use altogether (which will favor to using your system configurations).

GN: use_sysroot = false

**Comment by onny** [comment]
Appending ``use_jessie_sysroot=true`` did the trick 👍 
But still some errors ...
```
[15105/29106] SOLINK ./libozone.so
FAILED: libozone.so libozone.so.TOC 
python "/home/onny/projects/chromium-wayland-git/src/chromium/src/build/toolchain/gcc_solink_wrapper.py" --readelf="readelf" --nm="nm" --sofile="./libozone.so" --tocfile="./libozone.so.TOC" --output="./libozone.so"  -- ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -lpthread -Wl,--as-needed -fuse-ld=gold -B../../third_party/binutils/Linux_x64/Release/bin -Wl,--threads -Wl,--thread-count=4 -Wl,--icf=all -m64 -pthread -Werror --sysroot=../../build/linux/debian_jessie_amd64-sysroot -L/home/onny/projects/chromium-wayland-git/src/chromium/src/build/linux/debian_jessie_amd64-sysroot/lib/x86_64-linux-gnu -Wl,-rpath-link=/home/onny/projects/chromium-wayland-git/src/chromium/src/build/linux/debian_jessie_amd64-sysroot/lib/x86_64-linux-gnu -L/home/onny/projects/chromium-wayland-git/src/chromium/src/build/linux/debian_jessie_amd64-sysroot/usr/lib/x86_64-linux-gnu -Wl,-rpath-link=/home/onny/projects/chromium-wayland-git/src/chromium/src/build/linux/debian_jessie_amd64-sysroot/usr/lib/x86_64-linux-gnu -L/home/onny/projects/chromium-wayland-git/src/chromium/src/build/linux/debian_jessie_amd64-sysroot/usr/lib/gcc/x86_64-linux-gnu/4.6 -Wl,-rpath-link=/home/onny/projects/chromium-wayland-git/src/chromium/src/build/linux/debian_jessie_amd64-sysroot/usr/lib/gcc/x86_64-linux-gnu/4.6 -L/home/onny/projects/chromium-wayland-git/src/chromium/src/build/linux/debian_jessie_amd64-sysroot/usr/lib -Wl,-rpath-link=/home/onny/projects/chromium-wayland-git/src/chromium/src/build/linux/debian_jessie_amd64-sysroot/usr/lib -L../../build/linux/debian_jessie_amd64-sysroot/usr/lib/x86_64-linux-gnu -o "./libozone.so" -Wl,-soname="libozone.so" @"./libozone.so.rsp"
../../ui/ozone/platform/wayland/wayland_xkb_keyboard_layout_engine.cc:19: error: undefined reference to 'xkb_keymap_mod_get_index'
../../ui/ozone/platform/wayland/wayland_xkb_keyboard_layout_engine.cc:20: error: undefined reference to 'xkb_keymap_mod_get_index'
../../ui/ozone/platform/wayland/wayland_xkb_keyboard_layout_engine.cc:21: error: undefined reference to 'xkb_keymap_mod_get_index'
../../ui/ozone/platform/wayland/wayland_xkb_keyboard_layout_engine.cc:28: error: undefined reference to 'xkb_state_update_mask'
../../ui/ozone/platform/wayland/wayland_xkb_keyboard_layout_engine.cc:34: error: undefined reference to 'xkb_state_mod_index_is_active'
../../ui/ozone/platform/wayland/wayland_xkb_keyboard_layout_engine.cc:37: error: undefined reference to 'xkb_state_mod_index_is_active'
../../ui/ozone/platform/wayland/wayland_xkb_keyboard_layout_engine.cc:40: error: undefined reference to 'xkb_state_mod_index_is_active'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[15111/29106] CXX obj/url/mojo/url_mojom_origin_blink/origin.mojom-blink.o
ninja: build stopped: subcommand failed.
```
Maybe libxkbcommon in jessie is too old or the version is wrong?

**update**: I was able to fix this by editing the file ``ui/ozone/platform/wayland/BUILD.gn`` and changing:
```
pkg_config("wayland-egl") {
  packages = [ "wayland-egl" ]
}
```
to
```
pkg_config("wayland-egl") {
  packages = [ "wayland-egl" , "xkbcommon" ]
}

```
Now let's see if I can run chromium on wayland :)

**Comment by onny** [comment]
As soon as I've got everything up and running, I'll publish my ArchLinux package here: https://aur.archlinux.org/packages/chromium-wayland-git

Thanks @tonikitoo for the support!

**Comment by tonikitoo** [comment]
@onny what is the status? still seeing undefined references to xkb?

Update: answering myself, I just saw your update above. It builds.

In order to run, <our>/chrome --mus --ozone-platform=wayland should do the trick.

Also, I wonder whether you built the latest 'ozone-wayland-dev' branch? Basically, this is a development snapshot of Chromium Tip of Trunk, which is not a stable release baseline (m64/dev).

A month ago @msisov rebased our patches on top of m62/beta, for demonstration purposes. Maybe we should aim at something similar for packaging?

**Comment by onny** [comment]
The git version is fine for testing purpose. Further, the package I'm working on is labled as a git version.
I installed my chromium-wayland-git package, but can not run it :/
```
./chromium: error while loading shared libraries: libbindings.so: cannot open shared object file: No such file or directory
./chromium: error while loading shared libraries: libbase.so: cannot open shared object file: No such file or directory
```

**Comment by tonikitoo** [comment]
Ok, I believe you are producing "component builds", where various chromium components build as shared libraries (.so).

For the sake of distribution, I would try with "is_component_build = false" in your GN args (default is 'true').

**Comment by onny** [comment]
Yep, I forget to package the *.so files. Sorry!
Now if I try to run chrome like this: ``./chrome --mus --ozone-platform=wayland`` I get:
```
[1450:1450:1118/162041.554052:FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x7ff9fbe4b45b base::debug::StackTrace::StackTrace()
#1 0x7ff9fbe4a15c base::debug::StackTrace::StackTrace()
#2 0x7ff9fbeb337f logging::LogMessage::~LogMessage()
#3 0x7ff9f6228c0c content::ZygoteHostImpl::Init()
#4 0x7ff9f5581df1 content::(anonymous namespace)::SetupSandbox()
#5 0x7ff9f5581a93 content::BrowserMainLoop::EarlyInitialization()
#6 0x7ff9f5594463 content::BrowserMainRunnerImpl::Initialize()
#7 0x7ff9f558057f content::BrowserMain()
#8 0x7ff9f6da8786 content::RunNamedProcessTypeMain()
#9 0x7ff9f6daaadc content::ContentMainRunnerImpl::Run()
#10 0x7ff9f6da75c9 content::ContentMain()
#11 0x55734e944739 ChromeMain
#12 0x55734e9445e2 main
#13 0x7ff9e946ff6a __libc_start_main
#14 0x55734e9444c4 <unknown>

Received signal 6
#0 0x7ff9fbe4b45b base::debug::StackTrace::StackTrace()
#1 0x7ff9fbe4a15c base::debug::StackTrace::StackTrace()
#2 0x7ff9fbe4af6f base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7ff9fc2bfda0 <unknown>
#4 0x7ff9e94838a0 __GI_raise
#5 0x7ff9e9484f09 __GI_abort
#6 0x7ff9fbe48156 base::debug::(anonymous namespace)::DebugBreak()
#7 0x7ff9fbe48138 base::debug::BreakDebugger()
#8 0x7ff9fbeb3716 logging::LogMessage::~LogMessage()
#9 0x7ff9f6228c0c content::ZygoteHostImpl::Init()
#10 0x7ff9f5581df1 content::(anonymous namespace)::SetupSandbox()
#11 0x7ff9f5581a93 content::BrowserMainLoop::EarlyInitialization()
#12 0x7ff9f5594463 content::BrowserMainRunnerImpl::Initialize()
#13 0x7ff9f558057f content::BrowserMain()
#14 0x7ff9f6da8786 content::RunNamedProcessTypeMain()
#15 0x7ff9f6daaadc content::ContentMainRunnerImpl::Run()
#16 0x7ff9f6da75c9 content::ContentMain()
#17 0x55734e944739 ChromeMain
#18 0x55734e9445e2 main
#19 0x7ff9e946ff6a __libc_start_main
#20 0x55734e9444c4 <unknown>
  r8: 0000000000000000  r9: 00007fffb59895d0 r10: 0000000000000008 r11: 0000000000000246
 r12: 000055734e94449b r13: 00007fffb598ae40 r14: 0000000000000000 r15: 0000000000000000
  di: 0000000000000002  si: 00007fffb59895d0  bp: 00007fffb5989820  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007ff9e94838a0  sp: 00007fffb59895d0
  ip: 00007ff9e94838a0 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

**Comment by onny** [comment]
This is my recent package buildscript: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chromium-wayland-git
I'm going to recompile it with some changes, let's see if this fixes the bug obove ...

**Comment by onny** [comment]
Okay building chromium works now. For other issues, I'll open new bug reports. Thanks for the support!
